name: Flaky Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Mostly pass, sometimes fail
        run: |
          R=$((RANDOM % 10))
          if [ "$R" -lt 2 ]; then
            echo "Failing (20%)"
            exit 1
          else
            echo "Passing (80%)"
          fi

      - name: Flaky Detector
        if: always()
        uses: ozguryesilbas/flaky-detector@v1
